name: Deploy API Master

on:
  push:
    branches:
      - master  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify the Python version you are using

      - name: Rsync Node Directory
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='/private/' --exclude='/tmp/'
          path: /
          remote_path: ~/files/prod1
          remote_host: 3.15.144.253
          remote_port: 22
          remote_user: bevnotessh
          remote_key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Install dependencies and activate venv
        uses: appleboy/ssh-action@master
        with:
          host: 3.15.144.253
          username: bevnotessh
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/files/prod1
            ln -s ~/files/resources/prod/static ~/files/prod/static
            ln -s ~/files/resources/prod/private ~/files/prod/private
            virtualenv env
            source env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python main.py update_caches
