name: Deploy API Master

on:
  push:
    branches:
      - master  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rsync Node Directory
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='/cred/' --exclude='/logs/'
          path: /
          remote_path: ~/files/
          remote_host: 3.139.108.78
          remote_port: 22
          remote_user: sshuser
          remote_key: ${{ secrets.SSH_DEPLOY_KEY }}