name: Deploy API Master

on:
  push:
    branches:
      - master  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify the Python version you are using

      - name: Rsync Node Directory
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='/private/' --exclude='/tmp/'
          path: /
          remote_path: ~/files/
          remote_host: 18.117.10.19
          remote_port: 22
          remote_user: sshuser
          remote_key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Install dependencies and activate venv
        uses: appleboy/ssh-action@master
        with:
          host: 3.139.108.78
          username: sshuser
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/files/
            virtualenv env
            source env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            gunicorn --workers 5 --keep-alive 600 --graceful-timeout 300 --worker-class uvicorn.workers.UvicornWorker --bind unix:/run/gunicorn.sock main:app --daemon
